### ISSUE TITLE
florriek_helloWorld prints wrong string

### ISSUE THREAD

**Issue by FlorrieK** [Pierrepont/java-oop-help#1]
The program prints "No" when it should print "Hello World!"

**Comment by FlorrieK** [comment]
`//This is an example

public class helloWorld
{
    public static void main(String[] args)
    {
        Boolean thisProgramWorks = false;

        if(thisProgramWorks)
        {
            System.out.println("Hello World!");
        }
        else
        {
            System.out.println("No.");
        }
    }
}`

**Comment by a11ce** [comment]
Okay, I'll look at it now

**Comment by a11ce** [comment]
Did that help?

**Comment by FlorrieK** [comment]
Yes, it worked perfectly
