### ISSUE TITLE
Insertion Sort

### ISSUE THREAD

**Issue by SRemiNM** [Pierrepont/java-oop-help#2]
Insertion Sort prints out two different things, one is correct, one is not

**Comment by a11ce** [comment]
Please add explanatory comments, especially about `check`.

**Comment by a11ce** [comment]
If you've fixed your code yourself, replace the file in the repo with what works. (And add comments if possible to serve as a reference to others.)

**Comment by a11ce** [comment]
Nice fix, check spelling on line 8
