### ISSUE TITLE
Smallest Method

### ISSUE THREAD

**Issue by SRemiNM** [Pierrepont/java-oop-help#3]
Method Smallest does not work

**Comment by FlorrieK** [comment]
I don't see the method smallest. Could you post it along with your issue?

**Comment by SRemiNM** [comment]
public static int smallest(int[]arr, int index, int k){
        if(index==arr.length-1){
            return arr[index]<arr[k]?index:k;
        }
        if(arr[index]<arr[k]){
            return smallest(arr,index+1,index);
        }
        else{
            return smallest(arr,index+1,k);
        }
    }

**Comment by SRemiNM** [comment]
`public static int smallest(int[]arr, int index, int k){
        if(index==arr.length-1){
            return arr[index]<arr[k]?index:k;
        }
        if(arr[index]<arr[k]){
            return smallest(arr,index+1,index);
        }
        else{
            return smallest(arr,index+1,k);
        }
    }`

**Comment by a11ce** [comment]
@SRemiNM , could you remove one of the insertionSort files you've posted, and be sure the other is up-to-date and commented? Also, in the future, code should not be posted in issues but added to your file.

**Comment by a11ce** [comment]
Closed due to not referencing a file
